import type { Enemy } from "@/types/game";

/**
 * Fantasy genre bestiary — Day 20 Combat (combat-spec §6.4).
 *
 * Domain 2 frozen content. 14 enemies authored in code. Stats taken
 * verbatim from the §6.4 table; descriptions written for narration
 * (1 sentence each, fantasy flavor — not stat-block prose).
 *
 * Ladder progression:
 *   Tier 1 (xp 10-30):   giant_rat → goblin → wolf → skeleton
 *   Tier 2 (xp 40-75):   bandit → cultist → orc → zombie → brigand_archer
 *   Tier 3 (xp 90-200):  dire_boar → ogre → troll → specter
 *   Apex  (xp 350):      dragon_whelp
 *
 * `is_boss` is false on all 14 — bosses come from the WorldBible
 * main quest and from dungeon mid-boss tagging. `loot_table_id`
 * uses the stub pattern `fantasy_<id>_loot` so Day 21's real loot
 * tables can wire to these without touching the bestiary.
 */
export const FANTASY_BESTIARY: Enemy[] = [
  {
    id:              "fantasy_giant_rat",
    name:            "Giant Rat",
    description:     "A bristle-furred rodent the size of a small dog, eyes glittering with feverish hunger.",
    hp_range:        [4, 6],
    agi_mod:         2,
    str_mod:         -1,
    damage_die:      "1d4",
    armor_bonus:     0,
    xp_value:        10,
    loot_table_id:   "fantasy_giant_rat_loot",
    is_boss:         false,
    behavior_flavor: "scurrying biter",
  },
  {
    id:              "fantasy_goblin",
    name:            "Goblin",
    description:     "A wiry green-skinned scrapper clutching a notched blade, grinning yellowed teeth.",
    hp_range:        [6, 10],
    agi_mod:         1,
    str_mod:         0,
    damage_die:      "1d6",
    armor_bonus:     1,
    xp_value:        25,
    loot_table_id:   "fantasy_goblin_loot",
    is_boss:         false,
    behavior_flavor: "aggressive melee",
  },
  {
    id:              "fantasy_wolf",
    name:            "Wolf",
    description:     "A lean grey predator slinking low, breath fogging in the chill.",
    hp_range:        [8, 12],
    agi_mod:         3,
    str_mod:         1,
    damage_die:      "1d6",
    armor_bonus:     0,
    xp_value:        30,
    loot_table_id:   "fantasy_wolf_loot",
    is_boss:         false,
    behavior_flavor: "pack hunter",
  },
  {
    id:              "fantasy_skeleton",
    name:            "Skeleton",
    description:     "A lattice of yellowed bone bound by dark intent, rusted blade still in its grip.",
    hp_range:        [10, 14],
    agi_mod:         0,
    str_mod:         1,
    damage_die:      "1d6",
    armor_bonus:     1,
    xp_value:        40,
    loot_table_id:   "fantasy_skeleton_loot",
    is_boss:         false,
    behavior_flavor: "relentless undead",
  },
  {
    id:              "fantasy_bandit",
    name:            "Bandit",
    description:     "A road-worn brigand in patched leathers, blade already drawn at the sight of you.",
    hp_range:        [10, 16],
    agi_mod:         1,
    str_mod:         1,
    damage_die:      "1d8",
    armor_bonus:     1,
    xp_value:        50,
    loot_table_id:   "fantasy_bandit_loot",
    is_boss:         false,
    behavior_flavor: "desperate brigand",
  },
  {
    id:              "fantasy_cultist",
    name:            "Cultist",
    description:     "A robed figure with stained sigils on the cowl, mouthing a chant that scrapes the air.",
    hp_range:        [10, 14],
    agi_mod:         1,
    str_mod:         0,
    damage_die:      "1d6",
    armor_bonus:     0,
    xp_value:        50,
    loot_table_id:   "fantasy_cultist_loot",
    is_boss:         false,
    behavior_flavor: "fanatical chanter",
  },
  {
    id:              "fantasy_orc",
    name:            "Orc",
    description:     "A slab-shouldered warrior with tusked jaw and an axe scarred by old fights.",
    hp_range:        [16, 22],
    agi_mod:         0,
    str_mod:         3,
    damage_die:      "1d10",
    armor_bonus:     2,
    xp_value:        75,
    loot_table_id:   "fantasy_orc_loot",
    is_boss:         false,
    behavior_flavor: "brutal melee",
  },
  {
    id:              "fantasy_zombie",
    name:            "Zombie",
    description:     "A bloat-skinned corpse dragging itself forward on stiffened limbs, mouth working soundlessly.",
    hp_range:        [14, 20],
    agi_mod:         -2,
    str_mod:         2,
    damage_die:      "1d8",
    armor_bonus:     0,
    xp_value:        65,
    loot_table_id:   "fantasy_zombie_loot",
    is_boss:         false,
    behavior_flavor: "shambling rotter",
  },
  {
    id:              "fantasy_brigand_archer",
    name:            "Brigand Archer",
    description:     "A leather-clad bowman crouched in cover, arrow already nocked and aimed at your throat.",
    hp_range:        [10, 14],
    agi_mod:         2,
    str_mod:         1,
    damage_die:      "1d8",
    armor_bonus:     1,
    xp_value:        60,
    loot_table_id:   "fantasy_brigand_archer_loot",
    is_boss:         false,
    behavior_flavor: "ranged ambusher",
  },
  {
    id:              "fantasy_dire_boar",
    name:            "Dire Boar",
    description:     "A boar the size of a warhorse, tusks scarred by past kills and small black eyes fixed on yours.",
    hp_range:        [20, 28],
    agi_mod:         1,
    str_mod:         3,
    damage_die:      "2d4",
    armor_bonus:     2,
    xp_value:        90,
    loot_table_id:   "fantasy_dire_boar_loot",
    is_boss:         false,
    behavior_flavor: "charging beast",
  },
  {
    id:              "fantasy_ogre",
    name:            "Ogre",
    description:     "A hulking brute swinging a tree-limb cudgel, every step shaking dust from the rafters.",
    hp_range:        [30, 40],
    agi_mod:         -1,
    str_mod:         4,
    damage_die:      "2d6",
    armor_bonus:     2,
    xp_value:        150,
    loot_table_id:   "fantasy_ogre_loot",
    is_boss:         false,
    behavior_flavor: "massive bruiser",
  },
  {
    id:              "fantasy_troll",
    name:            "Troll",
    description:     "A tall sinewy horror with stretched grey hide, wounds knitting closed before your eyes.",
    hp_range:        [40, 55],
    agi_mod:         0,
    str_mod:         4,
    damage_die:      "2d6",
    armor_bonus:     3,
    xp_value:        200,
    loot_table_id:   "fantasy_troll_loot",
    is_boss:         false,
    behavior_flavor: "regenerating monster",
  },
  {
    id:              "fantasy_specter",
    name:            "Specter",
    description:     "A drifting shape of cold-blue mist with the suggestion of a face, hollow where eyes should be.",
    hp_range:        [18, 25],
    agi_mod:         3,
    str_mod:         1,
    damage_die:      "1d8",
    armor_bonus:     0,
    xp_value:        120,
    loot_table_id:   "fantasy_specter_loot",
    is_boss:         false,
    behavior_flavor: "incorporeal wraith",
  },
  {
    id:              "fantasy_dragon_whelp",
    name:            "Dragon Whelp",
    description:     "A young dragon the size of a destrier, scales smoking faintly, eyes the color of a forge.",
    hp_range:        [50, 70],
    agi_mod:         2,
    str_mod:         3,
    damage_die:      "2d8",
    armor_bonus:     4,
    xp_value:        350,
    loot_table_id:   "fantasy_dragon_whelp_loot",
    is_boss:         false,
    behavior_flavor: "apex predator",
  },
];
