-- Endless Worlds RPG — Art Cache (Patch B)
-- Run this in the Supabase SQL editor (Dashboard → SQL Editor → New Query)
--
-- Stores SVG pixel art generated by the art engine. Keyed by location_id so
-- revisits hit the cache instantly. session_id is recorded for RLS ownership
-- and to attribute the original generation back to a specific save slot.

CREATE TABLE IF NOT EXISTS public.art_cache (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id   text NOT NULL UNIQUE,
  session_id    uuid REFERENCES public.game_sessions(id) ON DELETE SET NULL,
  genre         text NOT NULL,
  scene_type    text NOT NULL,
  svg_content   text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS art_cache_location_id_idx ON public.art_cache (location_id);
CREATE INDEX IF NOT EXISTS art_cache_session_id_idx  ON public.art_cache (session_id);

ALTER TABLE public.art_cache ENABLE ROW LEVEL SECURITY;

-- Drop any prior versions of the policies so the migration is idempotent.
DROP POLICY IF EXISTS "Users can read own art cache"   ON public.art_cache;
DROP POLICY IF EXISTS "Users can insert own art cache" ON public.art_cache;

CREATE POLICY "Users can read own art cache"
  ON public.art_cache
  FOR SELECT
  USING (
    session_id IN (
      SELECT id FROM public.game_sessions WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own art cache"
  ON public.art_cache
  FOR INSERT
  WITH CHECK (
    session_id IN (
      SELECT id FROM public.game_sessions WHERE user_id = auth.uid()
    )
  );
